# Generated by Django 3.1.3 on 2020-11-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201103_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemons'},
        ),
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'verbose_name_plural': 'Pokemon Types'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainers'},
        ),
    ]
