# Generated by Django 3.1.3 on 2020-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201103_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
