# Generated by Django 3.1.3 on 2020-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201103_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
